@baseUrl = http://localhost:3000

### Create a new book
POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "publication_year": 1925,
  "isbn": "978-0-7432-7356-5"
  
}

### Get all books
GET {{baseUrl}}/books


### Create another book
POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "To Kill a Mockingbird",
  "author": "Harper Lee",
  "isbn": "978-0-06-112008-4",
  "publication_year": 1960
}

### Search for books by Harper Lee
GET {{baseUrl}}/books/author/Harper Lee

### Search for books with title containing "Mockingbird"
GET {{baseUrl}}/books/title/To Kill a Mockingbird


### Update book with ID 
PATCH {{baseUrl}}/books/5
Content-Type: application/json

{
  "publication_year": 1961
}

###DELETE book
DELETE {{baseUrl}}/books/4
